### ISSUE TITLE
Packet Script Support

### ISSUE THREAD

**Issue by ATCUSA** [la5nta/pat#114]
Our local area winlink connection uses a vhf node that connects to the uhf winlink gateway. Using RMS express you can handle this by using a connect script instead of the digipeater mode. The script would look like the following( anything after // is a comment and not used in the actual rms script.):
```
C K7LL-7 // Connects to Node
Connected // Looks for this keyword to be returned from the node. Not case sensitive.
C K7LL-10 // Tells the node to connect to the Winlink gateway
Connected
```
We are trying to move away from rms express over to pat for our local emergency communications team.

**Comment by martinhpedersen** [comment]
Hi - thanks for the proposal.

We got a similar feature request on [pat-users a while back](https://groups.google.com/forum/#!topic/pat-users/S3wfxTXn93c). Maybe you could discuss this further with Mike to ensure that both use-cases can be handled by this feature request?

The syntax from your example script seems to be somewhat ambiguous IMHO, with even/odd lines indicating send/expect. Is this a common syntax for node traversal? Maybe we could come up with something a tittle more flexible and robust(?).

From the top of my head:
1. An embedded scripting language [Lua?](https://github.com/yuin/gopher-lua)
2. Exec a process and connect stdin/stdout to the AX.25 stream (Use the returned status code to signal success/failure)
3. [Go's new plugin support](https://jeremywho.com/go-1.8---plugins/)
4. Define our own syntax. E.g. *(oh, please stop me...)*
    ```
        send "C K7LL-7\r\n"  // Connect to node
        wait "*[Cc]onnect.*" // Wait for line that matches this regular expression
    ```
5. Keep it simple (your proposal)

I think no 2. (exec) probably would be the most realistic solution with regards to implementation complexity and usage flexibility. With that approach, you could even plug in a custom parser to support what ever syntax you prefer.

What do you think?

**Comment by ATCUSA** [comment]
I think you are on to a good idea. I am pretty sure the idea is similar to what the other user was trying to describe. Basically instead of connecting through a digipeater we connect to a node and then have to tell that node to connect to the gateway. I can't say for certain that it is overly common, however, this is how RMS Express handles it. I think that number 2 is a good approach, but I also like the idea of going with the new go plugins. Please let me know if you need me to further clarify or if you need any help with testing things out since. Thanks again for all the work and time you put into this project.

Austin




---- On Mon, 18 Dec 2017 14:20:14 -0800 Martin Hebnes Pedersen &lt;notifications@github.com&gt; wrote ----




Hi - thanks for the proposal.

We got a similar feature request on pat-users a while back. Maybe you could discuss this further with Mike to ensure that both use-cases can be handled by this feature request?

The syntax from your example script seems to be somewhat ambiguous IMHO, with even/odd lines indicating send/expect. Is this a common syntax for node traversal? Maybe we could come up with something a tittle more flexible and robust(?).

From the top of my head:

An embedded scripting language Lua?

Exec a process and connect stdin/stdout to the AX.25 stream (Use the returned status code to signal success/failure)

Go's new plugin support

Define our own syntax. E.g. (oh, please stop me...) 

 send "C K7LL-7\r\n" // Connect to node wait "*[Cc]onnect.*" // Wait for line that matches this regular expression 

Keep it simple (your proposal)

I think no 2. (exec) probably would be the most realistic solution with regards to implementation complexity and usage flexibility. With that approach, you could even plug in a custom parser to support what ever syntax you prefer.

What do you think?

**Comment by martinhpedersen** [comment]
Hi again Austin,

I've done some research and preliminary tests on my suggested solution. It will be harder to implement than initially thought due to buffering in the system.

We may need to implement a pre-handshake hook in wl2k-go/fbb that redirects the output from the remote node for this to work properly. It would need to scan the remote stream line-by-line, and based on the content of the line, redirect it to the hook-script *or* send it to the handshake-procedure. The downside is that we will need to make some assumptions regarding line-feed etc. It complicated the solution quite a bit.

**Comment by DougCollinge** [comment]
It doesn't seem that nasty to do this the way Winlink Express does it; i.e., inserting a node "dialing" protocol at the beginning of each ax.25 connection. The dialing scripts don't need to be complicated so it wouldn't be a heavy addition. I kind of think that the administrative burdens involved in using a plugin or spawning an external function would be greater, in fact. Winlink Express has files for scripts, which would be ugly, IMHO. Probably nicer and more idiomatic to add dialing parameters to the connection URLs. E.g. something like:
ax25:///VE7GNU?connect=VE7NOD?expect=CONNECTED&connect=VE7GNU-10&expect=CONNECTED&end
If this must eventually be made more user-friendly then something can read the config file, present a nice GUI to edit these and whatever else, then write it back.

I'm interested in this issue because around here there are lots of nodes and no digipeaters, I guess because digipeaters are disfavoured.

**Comment by rymcol** [comment]
My local repeater also has a Winlink gateway behind a connection script selector, and this would be a game changer for me

**Comment by martinhpedersen** [comment]
This has been discussed recently @ pat-users. https://groups.google.com/g/pat-users/c/kLCOqMq26Mk.

I still think option 2 (exec a script) would be the most flexible solution. However, we must also make sure it's easy to use. Not everyone is comfortable writing bash scripts.

So I'm thinking maybe we should implement the exec option, and as a step 2 provide a default script that takes some parameters to support the most common use-case(s).

It would probably take me a couple of hours to implement the exec-part, if we keep it very simple. Then we could start experimenting with a script, and at the end port this script to Go and include it as a built-in function to make sure it works on all platforms.

Proposed protocol:
1. Pat connects to the node
2. Pat spawns the script.
    - The first argument is the callsign of the dialed station.
    - An arbitrary (0..N) number of additional user-supplied parameters follows. These are given as Dial URL parameters.
    - Traffic is forwarded via stdin/stdout.
    - stderr is forwarded to the terminal.
4. After the script terminates, Pat uses the exit status (0 == success) to determine if the node traversal was successful or not. If it was successful, the connection is carried on as normal.

**Comment by martinhpedersen** [comment]
In order to come up with a good default script, it is important to gather as much real-world examples as possible. Asking for input on the pat-users mailing list should be a place to start. Also, I imagine there might be examples scattered around the internet by Winlink Express users that already do this. Anyone up for this task?

**Comment by martinhpedersen** [comment]
Had a chance to work a bit on this. While implementing a prototype I realized we can use environment variables to pass additional useful information. So we don't need to reserve the first argument for the remote stations callsign. Much easier passing it as an environment variable 😄
