### ISSUE TITLE
Unable to add path to fs watcher: no space left on device

### ISSUE THREAD

**Issue by debarber** [la5nta/pat#119]
After having install this on Ubuntu 17.10, I am presented with the following error when I use 'pat http'.  

2018/02/08 13:57:10 Unable to add path '/home/david/.wl2k/mailbox/VE7BU/in' to fs watcher: no space left on device

Any suggestions?  The drive is definitely not full.  

Thank you

**Comment by thebaltee** [comment]
Followup to this.  The issue is permissions.  executing "sudo pat http" instead of "pat http", resolves the problem.

**Comment by martinhpedersen** [comment]
**You should never run pat as root.**

> 2018/02/08 13:57:10 Unable to add path '/home/david/.wl2k/mailbox/VE7BU/in' to fs watcher: no space left on device
This error suggests that the partition for `/home/david` was full.

Running Pat with `sudo` will change the default mailbox directory from your user's home directory (/home/david/.wl2k/) to your root directory (/root/.wl2k/). If you have a separate partition for `/home`, then that would explain why the error disappeared, since you pointed Pat to store data to another device that apparently was not full.

The cause of initial error: There was no space left on device.

**Comment by martinhpedersen** [comment]
@debarber - Did you resolve the issue?

**Comment by martinhpedersen** [comment]
Please re-open the issue if you were not able to resolve the issue other than to run Pat as root.
