### ISSUE TITLE
Import emails from Winlink Express

### ISSUE THREAD

**Issue by xylo04** [la5nta/pat#205]
Brian Hoobler asked in the [mailing list](https://groups.google.com/d/topic/pat-users/NxVMYcKJn-c/discussion) to be able to import archived Winlink Express messages into Pat's mailbox.

**Comment by martinhpedersen** [comment]
I believe it would be better to implemented this as a separate tool rather than encompassing it as a feature in Pat. The [fbb package](https://godoc.org/github.com/la5nta/wl2k-go/fbb#Message) provides everything needed to encode/decode messages in the B2F message format we use to store messages on disk.

By the way, Winlink Express does this conversion when encoding the message for transfer over the air. So maybe ask if they are willing to provide a feature to export messages to the B2F format? That would save someone from having to reverse engineer the format Winlink Express uses to store messages on disk.

**Comment by martinhpedersen** [comment]
PS: A hack could be to send all the messages over "telnet" from Winlink Express to Pat. I don't know how convenient that would be though. I guess it depends on how easy it is to move mutiple messages from inbox to outbox, and get Winlink Express to deliver them to Pat.. possibly by making Pat identify as a CMS or relay node.

If someone is willing to give it a shot, please comment on this issue :)

Closing this issue for now since this is out of scope for this project, IMHO.

**Comment by jboverfelt** [comment]
In case anyone's interested, I just whipped this up:

https://git.sr.ht/~jboverfelt/exp2pat

Seems to work fine with the Winlink Express xml exports. I'm sure there are some bugs/rough edges since the XML format is (of course) undocumented.
