### ISSUE TITLE
GUI: Add a button and API method for aborting connect/session

### ISSUE THREAD

**Issue by martinhpedersen** [la5nta/pat#24]
Similar to ctrl+c in the command-line interface.

**Comment by DougCollinge** [comment]
I checked out the develop branch just to try out this feature but I keep getting the old html, not what is in the template. How do you flush the cache or whatever you have to do to get the html to regenerate?

**Comment by martinhpedersen** [comment]
@DougCollinge - Run `go generate` in the project's root directory :)

**Comment by DougCollinge** [comment]
Shouldn't that be in the make.bash script?

**Comment by DougCollinge** [comment]
I'm testing this new feature and it is good. It does do one weird thing, though: if you click on disconnect before a station has connected (i.e., a number of ConReq have gone out but no answer received) then it sends a series of Disc to a station that evidently won't hear them and which would be confused anyway, since there is no connection to disconnect. I would expect it to just quietly abort the connect sequence in this circumstance.

**Comment by martinhpedersen** [comment]
> Shouldn't that be in the make.bash script?

https://github.com/la5nta/pat/pull/173#issuecomment-560482966

**Comment by martinhpedersen** [comment]
Regarding the DISC frames: What you are seeing the the normal (gracefull) disconnect of an ongoing ARDOP ARQ connection in it's dialing phase. Winlink Express have the same behaviour.

You should see a "click to force disconnect" tooltip appearing, which (if clicked) will send a force disconnect command to the TNC to make it terminate the dial/conn immediately.

I can't say for sure why the deveopers of the ARDOP (and WINMOR) protocol decided not to abort the dialing sequence immediately when a disconnect command is sent from the host app, but I beilieve it may be due to the fact that the remote node might have heard the CONN frames even though the local node is not able to receive the answer. If the local node then suddenly aborts the dialing, the remote might be left in an "answering a call" state until a timeout is reached.

**Comment by DougCollinge** [comment]
I had to use Winlink Express yesterday and you are right, that's how it works. I think it is very likely the reason is what you said, even if I think that is not well thought out. The reason I never noticed is that I always just hit the 'abort' button whenever I become convinced that the receiver can't hear me or isn't going to answer for some reason.

**Comment by martinhpedersen** [comment]
> The reason I never noticed is that I always just hit the 'abort' button whenever I become convinced that the receiver can't hear me or isn't going to answer for some reason.

Heh, I do the same ;-) But you're able to send the force disconnect command by clicking the "disconnect button" a second time right?

**Comment by DougCollinge** [comment]
Yes, that seems to work. But I am currently trying to reliably reproduce some edge cases where it seems to go wrong.

One thing I noticed today is that, if the tnc is "waiting for a clear channel" the disconnect feature doesn't work at all. That's one of the main reasons you might want to abort the connection attempt.

**Comment by DougCollinge** [comment]
If I disconnect a station that is already connected it puts "Got abort signal, disconnecting..." into the log, then sends DISC the first time it gets an IDLE, then it puts "Disconnecting..." in the status field, and never changes it. Clicking on "Disconnecting..." does not do anything, so I can't use that to start a connect, which is how I do it every time now :-)

Since I am listening on my AX.25 interface I expect it to go back to "Listening ax25" but it doesn't.

**Comment by martinhpedersen** [comment]
I'm assuming you are referring to ARDOP disconnection. Are you using ARDOPc or ARDOP_WIN?

If I understand you correctly, the status field text changed to "Disconnecting..." and the ARDOP TNC started to send DISC frames. However, when the disconnection was complete the status bar text did not reset?

Thanks for testing!

**Comment by DougCollinge** [comment]
I am using ardopc and yes, the TNC sends DISC, then abandons but leaves the status bar showing "disconnecting..."

I'm pretty sure this happens any time you try to disconnect a live, connected session.
