### ISSUE TITLE
Pactor: Exchange failed: unexpected EOF

### ISSUE THREAD

**Issue by K7LRK** [la5nta/pat#248]
Pactor seems to be working -- my script uses these commands:

echo Attempting a connection with <call sign> using pactor
pat connect pactor:///<Call Sign>

The terminal displays:
============
Attempting a connection with K7NHV using pactor
2021/04/06 13:13:37 Unable to get frequency from rig network: dial tcp [::1]:4532: connect: connection refused.
2021/04/06 13:13:40 Connecting to K7NHV (pactor)...
2021/04/06 13:13:42 Connected to K7NHV (pactor)
2021/04/06 13:14:27 Exchange failed: unexpected EOF
=============

the test email was created using the web-GUI (had to add .txt to get this interface to accept the attachment)

[WBWNQQAXPLIT.b2f.txt](https://github.com/la5nta/pat/files/6267578/WBWNQQAXPLIT.b2f.txt)

BTW: I wanted to use the pat-users group but can not find a "new message" option.  So 2nd issue is the google group site not allowing new messages.

73,
Clark
K7LRK

**Comment by harenber** [comment]
The "unexpected EOF" usually means, that the underlying transport layer (PACTOR in this case) has received a disconnect event (bad conds?).

To use Google Groups I suggest to just read the documentation: https://support.google.com/groups/answer/1046523

73s
Torsten DL1THM

**Comment by martinhpedersen** [comment]
@K7LRK - What Torsten means by "bad conds" is poor radio conditions, aka weak signal and/or a poor [signal-to-noise-ratio](https://en.wikipedia.org/wiki/Signal-to-noise_ratio).

Torsten seems to think that this problem is not with Pat, but rather an issue with your radio/modem. The fact that your connection is terminated after quite some time of inactivity led me to believe the same thing. My advice would be to post a video at the pat-users community forum of what's going on (including audio from your rig). It should provide enough information for people to help you out 🙂 

Since we're not seing any evidence suggesting that this is a bug in Pat, I'm closing this issue for now.

**Comment by K7LRK** [comment]
Yes, I believe this is not a PAT issue.

Thanks for the followup

Clark
