### ISSUE TITLE
Add an arm64 .deb binary release

### ISSUE THREAD

**Issue by xylo04** [la5nta/pat#321]
Now that Raspberry Pi OS 64-bit is officially supported, we should create `.deb` release packages appropriate for the `arm64` architecture.

**Comment by harenber** [comment]
Feel free to use this [package](https://harenber.web.cern.ch/harenber/pat_0.12.1_arm64.deb) (private build) until there is an official version. 

I just applied minimal changes to the debian package directory to get the build process through.

**Comment by martinhpedersen** [comment]
Can anyone with a 64 bit Raspberry Pi OS install confirm that this is working?
https://share.priv.getpat.io/pat_0.12.1_arm64.deb

Thanks!

**Comment by harenber** [comment]
@martinhpedersen your package installs and starts fine. Can do more test tomorrow. Contact me (PM) if you wanna have shell access to a Pi4 with 64bit OS.

73s! Torsten

**Comment by martinhpedersen** [comment]
Thanks @harenber 🙂 

I don't think we need to test all the functionality. If it installs and executes, then most likely it runs just fine 👍  The deb was built in a Docker container (debian image) using Docker's new multi-arch support 🎉 

The only thing I can think of is the `libax25` part, since that is C code and built using a different compiler. If anyone could verify that `pat connect ax25:///FOOBAR` works as well, that would be a big bonus. You don't have to make a connection. Just get it far enough to start dialing 🙂  IIRC you can use any tty device. The kernel does not check for a KISS compliant device before it starts to send AX.25 connect frames.

**Comment by harenber** [comment]
Hi @martinhpedersen,

here you are (don't get confused by the host name `cubietruck`, the device is a Pi4 (which replaced a Cubietruck and I kept the hostname):

```
pi@cubietruck:~ $ pat connect ax25:///DL0AAA
2022/02/18 10:15:46 Connecting to DL0AAA (ax25)...
^C2022/02/18 10:15:53 Transport ax25's dialer can not be aborted at this stage
2022/02/18 10:15:53 Unable to establish connection to remote: Dial timeout
```

`axlisten -a` shows:

```
wl2k: fm DL1THM to DL0AAA ctl SABM+ 10:15:46.294450
wl2k: fm DL1THM to DL0AAA ctl DISC+ 10:15:53.610116
```

```
pi@cubietruck:~ $ dpkg  --print-architecture
arm64
pi@cubietruck:~ $ dpkg -s pat
Package: pat
Status: install ok installed
Priority: extra
Section: ham
Installed-Size: 10100
Maintainer: Martin Hebnes Pedersen <martin.h.pedersen@gmail.com>
Architecture: arm64
Version: 0.12.1
Replaces: wl2k-go
Recommends: libhamlib-utils (>= 1.2), ax25-tools, gpsd (>= 2.90)
Suggests: tmd710-tncsetup
Conflicts: dist, wl2k-go
Description: A portable Winlink client for amateur radio email.
Homepage: http://getpat.io
pi@cubietruck:~ $
```

Looks good to me 😄 👍 

73s

 Torsten

**Comment by martinhpedersen** [comment]
Perfect 👌 Thanks Torsten 🙂
