### ISSUE TITLE
Issue with Hurricane form?

### ISSUE THREAD

**Issue by georges** [la5nta/pat#358]
There seems to be a problem with the Hurricane form not opening back up once attached.

STR

1. pat http
2. Action -> Compose
3. Template -> WEATHER Forms -> Hurricane Report
4. Fill out some info and press submit
5. Go to your sent folder
6. Open message
7. Click on Hurricane Report Initial button

Result:

- A browser window opens and says: "open: no such filed or directory"

Expected result:

- Form should show up in browser again

Looking at the saved message on the file system, it does contain the form

Possible that the form name having white spaces is messing things up.

**Comment by richcannings** [comment]
I reproduced the error and can take a look at the code.

When the URL parameter is `rendertohtml=true`, the error `open: no such filed or directory` is displayed.

When the URL parameter is `rendertohtml=false`, the correct XML file is displayed.

All the other forms I tried work as intended.

**Comment by richcannings** [comment]
Stopping my debugging for the day and noting the issue here so I don't forget:

In the Standard_Forms path, both `MAPPING-GIS FORMS` and `WEATHER Forms` contain a file named `Hurricane Report.txt`.

When `forms#RenderForm` calls `forms#findFormFromURI`, it returns `form` containing the *first path* with `Hurricane Report.txt`. In this case, it is incorrectly returning `MAPPING-GIS FORMS/...`, and the `form#TextFileURI`, `form#InitialURI`, and `form#ViewerURI` are incorrect. It should be returning paths with `WEATHER Form/...`

Thus, we/I need to figure out how to ensure we return correct path when there are duplicate file names in different paths.
