### ISSUE TITLE
PTT -- w/o full rig control

### ISSUE THREAD

**Issue by fishhack66** [la5nta/pat#41]
Hello, All. (esp. Martin @martinhpedersen )

I have everything working well (Pat and WINMOR) with one exception: controlling the PPT line via a simple RS-232/one-transister switch, without full CAT/CI-V rig control.  I have Icom radios, but no CI-V control converter box. 

I tried to set definitions with rigctld, but just managed to mess up things up and nothing in Pat would work at all.  I'm back to a clean install and config file, and I can get everything working properly with VOX ptt, but that is where success ended (no connects, VOX circuit not nearly fast enough for WINMOR).

My question: how would I set up Pat's congif file to set the serial RTS line high, thus closing the PTT circuit via my simple little interface, but not using any form of remote (CAT/CI-V) rig control?  In other words, to get it to function exactly as FlDigi or packet does?  :^)  I think such a set-up would benefit many hams, especially those on a budget.

Any ideas would be appreciated.

Best regards and 73,
Dave Hassler
K7CCC

**Comment by martinhpedersen** [comment]
Hi Dave,

thanks for your interest in Pat and this great question :)

Could you be so kind to re-post your question in the [user community mailing list](https://groups.google.com/group/pat-users)? The user community is a great place to discuss usage related questions because it has a much broader audience. I would love to have this question listed there amongst all other (future) discussions regarding configuration of Pat in various environments.

I do believe it is already possible to use such an interface with Pat, through rigctld's ```--ptt-type=RTS``` option. Pat's rigcontrol config section would be identical to other setups. I believe the key to this problem is to tell rigtctld to use RTS for ptt control.

I would be glad to further discuss this in the user community list where we may even be able to reach users that already have this kind of configuration up and running :) 

-- 
73 de LA5NTA

**Comment by martinhpedersen** [comment]
Thanks for re-posting on the user community list :)

For future reference, this conversation continued at https://groups.google.com/forum/#!topic/pat-users/gofrbmvLP6Q.
