### ISSUE TITLE
Wiki Edit: macOS instructions should use Homebrew to install

### ISSUE THREAD

**Issue by kd8drx** [la5nta/pat#49]
Mac ports is is generally considered deprecated by the community, and is not recommended due to how it installs packages and modifies the OS. The preferred tool by most macOS users is Homebrew (brew.sh), which is far easier to install and itself installs packages to /usr/local, thus preventing issues with SIP that generic *nix apps may run afoul of.

Package names are generally the same between the two. For example, to install hamlib the command would be `brew install hamlib`.

I'm happy to edit those entries if given the privileges.

**Comment by martinhpedersen** [comment]
Oh, I see. Thanks, it's been a while since I last used Mac OS on a daily basis. We should probably add a sentence about how to install brew also.

Hmm... Apparently there is no way to give wiki write privileges to one user, bummer. Maybe you could fork the wiki-repo and make the changes there so I could pull the changes from you? (http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github)

If that is too much pain, I can just edit it myself. No problem!

**Comment by martinhpedersen** [comment]
I've replaced the one remaining example on our wiki involving macports with homebrew now.

Thanks!
